# **Task 40: NumPy — Random Numbers**

**Student Name:** Qalb E Zahra Mashhadi  
**Program:** NAVTTC — Artificial Intelligence (ML & DL)  

---

## **1. Objective**

The objective of this task is to learn how to generate **Pseudo Random Numbers** using NumPy's `random` module. We will explore how to generate random integers, floats, and multi-dimensional arrays, as well as how to pick random values from a predefined set using the `choice()` method.

---

## **2. Learning Outcomes**

* **Pseudo vs. True Random:** Understanding that computers use algorithms to generate "pseudo-random" numbers which are predictable if the algorithm is known, whereas true random numbers require external physical input.

* **Random Integers:** Using `randint()` to generate whole numbers within a specific range.

* **Random Floats:** Using `rand()` to generate decimal values between `0` and `1`.

* **Random Arrays:** Learning to use the `size` parameter to create **1-D** or **2-D** arrays filled with random data instantly.

* **Random Choice:** Mastering `random.choice()`, which picks random elements from a provided array, making it highly useful for sampling data.

---

## **3. Conclusion**

Random numbers are at the heart of **Machine Learning and Data Science**. They are used for initializing weights in **Neural Networks**, shuffling datasets to prevent bias, and creating synthetic data for testing. Mastering NumPy's `random` module allows you to introduce controlled **stochasticity** (randomness) into your AI models, ensuring they generalize better on unseen data.

In [1]:
from numpy import random
import numpy as np

# --- 1. Generating Single Random Values ---
# Random integer from 0 to 100

int_val = random.randint(100)
print(f"Random Integer (0-100): {int_val}")

# Random float between 0 and 1

float_val = random.rand()
print(f"Random Float (0-1): {float_val}")

Random Integer (0-100): 38
Random Float (0-1): 0.21085435834704946


In [2]:
# --- 2. Generating Random Arrays ---
# 1-D array with 5 random integers (0-100)

arr_1d_int = random.randint(100, size=(5))
print("1-D Random Integer Array:", arr_1d_int)

# 2-D array (3 rows, 5 columns) of random integers

arr_2d_int = random.randint(100, size=(3, 5))
print("\n2-D Random Integer Array:\n", arr_2d_int)

# 2-D array (3 rows, 2 columns) of random floats

arr_2d_float = random.rand(3, 2)
print("\n2-D Random Float Array:\n", arr_2d_float)

1-D Random Integer Array: [21 38 51 70 16]

2-D Random Integer Array:
 [[29 60 59 42 63]
 [65 20  8 76 92]
 [19 77 66 44 30]]

2-D Random Float Array:
 [[0.43936034 0.9565275 ]
 [0.21379352 0.41452033]
 [0.39627037 0.67225195]]


In [3]:
# --- 3. Random Choice from an Array ---
# Pick one random value from the list

pick = random.choice([3, 5, 7, 9])
print(f"Random choice from [3, 5, 7, 9]: {pick}")

# Pick values from the list to form a 2-D array
pick_array = random.choice([3, 5, 7, 9], size=(3, 5))
print("\nRandom Choice Array (3x5):\n", pick_array)

Random choice from [3, 5, 7, 9]: 9

Random Choice Array (3x5):
 [[7 9 7 5 3]
 [5 3 3 3 7]
 [9 7 3 7 7]]
