# **Task 33: NumPy — Array Shape**

**Student Name:** Qalb E Zahra Mashhadi  
**Program:** NAVTTC — Artificial Intelligence (ML & DL)  

---

## **1. Objective**

The objective of this task is to understand the **Shape** attribute in NumPy. The shape of an array represents the number of elements in each of its dimensions. We will learn how to retrieve this information using the `.shape` attribute and interpret the resulting tuple for both simple and high-dimensional arrays.

---

## **2. Learning Outcomes**

- **Shape Attribute:** Understanding that `.shape` returns a tuple where each index represents the number of elements in that specific dimension.

- **Interpreting the Tuple:** - For a **2-D array**, a result of `(2, 4)` means 2 rows and 4 columns.
    - For **high-dimensional arrays**, the index in the tuple corresponds to the depth and size of each dimension.

- **High-Dimensional Shapes:** Observing how the `ndmin` argument affects the shape of an array, especially when padding dimensions to meet specific structural requirements.

- **Dimensional Verification:** Learning that the length of the shape tuple is always equal to the number of dimensions (`ndim`).

---

## **3. Conclusion**

In Artificial Intelligence and Deep Learning, **"Shape"** is perhaps the most frequently checked attribute. Whether you are feeding data into a **Neural Network** or performing matrix multiplication, ensuring that the shapes of your input tensors match the requirements of the model is critical to avoiding structural errors.

In [2]:
import numpy as np

# --- 1. Checking Shape of a 2-D Array ---
# This array has 2 rows and 4 columns

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("2-D Array:")
print(arr_2d)
print("Shape of the array:", arr_2d.shape)

# Result (2, 4) means 2 dimensions, first has 2 elements, second has 4.

2-D Array:
[[1 2 3 4]
 [5 6 7 8]]
Shape of the array: (2, 4)


In [3]:
# --- 2. Shape of a 1-D Array ---

arr_1d = np.array([1, 2, 3, 4])
print("Shape of 1-D array:", arr_1d.shape)

# Result (4,) means it has one dimension with 4 elements.

Shape of 1-D array: (4,)


In [4]:
# --- 3. Shape with High Dimensions (ndmin) ---
# Creating an array with 5 dimensions

arr_5d = np.array([1, 2, 3, 4], ndmin=5)

print("5-Dimensional Array:")
print(arr_5d)
print("\nShape of 5-D array:", arr_5d.shape)

"""
Interpreting (1, 1, 1, 1, 4):
- The 1st, 2nd, 3rd, and 4th dimensions have 1 element each.
- The 5th (innermost) dimension has 4 elements.
"""

5-Dimensional Array:
[[[[[1 2 3 4]]]]]

Shape of 5-D array: (1, 1, 1, 1, 4)


'\nInterpreting (1, 1, 1, 1, 4):\n- The 1st, 2nd, 3rd, and 4th dimensions have 1 element each.\n- The 5th (innermost) dimension has 4 elements.\n'

In [5]:
# --- 4. Comparing ndim and shape ---

print("Verification:")
print("\nNumber of dimensions (ndim):", arr_5d.ndim)
print("\nLength of shape tuple:", len(arr_5d.shape))

Verification:

Number of dimensions (ndim): 5

Length of shape tuple: 5
