# **Task 37: NumPy — Splitting Array**

**Student Name:** Qalb E Zahra Mashhadi  
**Program:** NAVTTC — Artificial Intelligence (ML & DL)  

---

## **1. Objective**

The objective of this task is to learn how to **Split** a single NumPy array into multiple sub-arrays. Splitting is essentially the reverse of joining. We will explore the `array_split()` method, learn how it handles uneven splits, and understand how to split multi-dimensional arrays along different axes (rows vs. columns).

---

## **2. Learning Outcomes**

- **Array Splitting Basics:** Using `np.array_split()` to break an array into a specified number of parts. The result is returned as a Python list containing the sub-arrays.

- **Handling Uneven Elements:** Understanding that `array_split()` is superior to the standard `split()` function because it automatically adjusts the size of the sub-arrays if the total number of elements isn't perfectly divisible.

- **2-D Array Splitting:** - **Row-wise (Default):** Splitting a matrix horizontally along the rows.
    - **Column-wise (Axis=1):** Splitting a matrix vertically using `axis=1` or `np.hsplit()`.

- **Specialized Functions:** Identifying helpers like `vsplit()` (vertical split) and `hsplit()` (horizontal split) as convenient alternatives for specific dimensional splits.

---

## **3. Conclusion**

Splitting is a vital operation in data preprocessing. For example, when training a **Machine Learning model**, we often split our main dataset into distinct chunks for **cross-validation** or to separate input features from target labels. Mastering `array_split()` ensures you can partition data flexibly regardless of the dataset size or structure.

In [1]:
import numpy as np

# --- 1. Basic 1-D Splitting ---

arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 parts

newarr = np.array_split(arr_1d, 3)
print("Splitting into 3 parts:")
print(newarr)

# Accessing individual split arrays

print("\nFirst part:", newarr[0])
print("Second part:", newarr[1])

Splitting into 3 parts:
[array([1, 2]), array([3, 4]), array([5, 6])]

First part: [1 2]
Second part: [3 4]


In [2]:
# --- 2. Handling Uneven Splits ---
# 6 elements into 4 parts (NumPy adjusts from the end)

uneven_split = np.array_split(arr_1d, 4)
print("Uneven split (6 elements into 4 parts):")
print(uneven_split)

Uneven split (6 elements into 4 parts):
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [3]:
# --- 3. Splitting 2-D Arrays (Matrices) ---

arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

# Default split (along rows)

row_split = np.array_split(arr_2d, 3)
print("2-D Split along rows (Default):")
for i, sub_arr in enumerate(row_split):
    print(f"Part {i+1}:\n{sub_arr}")

2-D Split along rows (Default):
Part 1:
[[1 2]
 [3 4]]
Part 2:
[[5 6]
 [7 8]]
Part 3:
[[ 9 10]
 [11 12]]


In [4]:
# --- 4. Splitting along Axis 1 (Columns) ---

arr_wide = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Using axis=1 to split columns

col_split = np.array_split(arr_wide, 3, axis=1)
print("2-D Split along columns (axis=1):")
print(col_split)

# Alternate: Using hsplit()

h_split_arr = np.hsplit(arr_wide, 3)
print("\nSplit using hsplit():")
print(h_split_arr)

2-D Split along columns (axis=1):
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

Split using hsplit():
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
