# **Task 34: NumPy — Array Reshaping**

**Student Name:** Qalb E Zahra Mashhadi  
**Program:** NAVTTC — Artificial Intelligence (ML & DL)  

---

## **1. Objective**

The objective of this task is to understand how to change the structure of an array using **Reshaping**. Reshaping allows us to add or remove dimensions or change the number of elements in each dimension without changing the actual data. We will also explore flattening and the use of unknown dimensions.

---

## **2. Learning Outcomes**

- **Reshape Logic:** Understanding that an array can only be reshaped if the total number of elements remains the same ($Product\ of\ dimensions = Total\ elements$).

- **1-D to Multi-D:** Learning to convert flat arrays into matrices (**2-D**) or tensors (**3-D**) for advanced computations.

- **Copy vs View:** Learning that `.reshape()` typically returns a **View**, meaning it refers back to the original array's data and does not create a new memory buffer.

- **Unknown Dimension (-1):** Using `-1` as a placeholder for one dimension, allowing NumPy to automatically calculate the correct size based on the other dimensions.

- **Flattening:** Converting any multi-dimensional array back into a simple 1-D array using `.reshape(-1)` or `.flatten()`.

---

## **3. Conclusion**

Reshaping is a fundamental operation in machine learning pipelines. For example, when processing images, we often need to reshape a 2D pixel grid into a 1D vector for a neural network input layer. Mastering the `-1` notation and understanding that reshaping creates a view helps in writing memory-efficient and flexible code for complex AI models.

In [1]:
import numpy as np

# --- 1. Reshape From 1-D to 2-D ---
# 12 elements into 4 rows and 3 columns (4 * 3 = 12)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = arr.reshape(4, 3)

print("1-D to 2-D (4x3):")
print(arr_2d)

1-D to 2-D (4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
# --- 2. Reshape From 1-D to 3-D ---
# 12 elements into (2 matrices, 3 rows, 2 columns) -> 2 * 3 * 2 = 12

arr_3d = arr.reshape(2, 3, 2)

print("1-D to 3-D (2x3x2):")
print(arr_3d)

1-D to 3-D (2x3x2):
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
# --- 3. Unknown Dimension (-1) ---
# We specify 2x2 and let NumPy decide the last dimension
# For 8 elements, 2*2*x = 8 -> x = 2

arr_8 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr_auto = arr_8.reshape(2, 2, -1)

print("Using Unknown Dimension (-1):")
print(newarr_auto)
print("\nCalculated Shape:", newarr_auto.shape)

Using Unknown Dimension (-1):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Calculated Shape: (2, 2, 2)


In [4]:
# --- 4. Flattening Arrays ---
# Converting Multi-D back to 1-D

multi_arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = multi_arr.reshape(-1)

print("Flattened Array:")
print(flat_arr)

Flattened Array:
[1 2 3 4 5 6]


In [6]:
# --- 5. Error Handling: Invalid Reshape ---

try:
    invalid_reshape = arr_8.reshape(3, 3)
except ValueError as e:
    print("Expected Error:", e)

Expected Error: cannot reshape array of size 8 into shape (3,3)
