# **Task 39: NumPy — Sorting Arrays**

**Student Name:** Qalb E Zahra Mashhadi  
**Program:** NAVTTC — Artificial Intelligence (ML & DL)  

---

## **1. Objective**

The objective of this task is to understand how to **Sort** NumPy arrays. Sorting refers to arranging elements in a specific order, such as numerical ascending or alphabetical. We will learn how to use the `np.sort()` function, how it handles different data types (strings, booleans), and how it sorts multi-dimensional arrays.

---

## **2. Learning Outcomes**

- **Array Sorting Basics:** Using `np.sort()` to return a sorted copy of the array. It is important to note that this method does **not** modify the original array (it returns a copy).

- **Data Type Flexibility:** Learning that NumPy can efficiently sort:
    - **Integers/Floats:** Ascending numeric order.
    - **Strings:** Alphabetical order.
    - **Booleans:** Where `False` (0) comes before `True` (1).

- **2-D Array Sorting:** Understanding that sorting a matrix typically sorts each row individually along the last axis by default.

- **Copy vs In-place:** Recognizing that `np.sort(arr)` returns a copy, which is different from the Python list `.sort()` method that modifies the original list in-place.

---

## **3. Conclusion**

Sorting is a fundamental preprocessing step in many **AI algorithms**. For example, it is required for efficient searching (Binary Search), identifying the top-k features in a dataset, or organizing time-series data. Mastering NumPy's sorting capabilities allows for quick data organization across complex, multi-dimensional structures, ensuring your data is in the correct order for model consumption.

In [1]:
import numpy as np

# --- 1. Basic Numerical Sorting ---

arr = np.array([3, 2, 0, 1])
sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)

Original Array: [3 2 0 1]
Sorted Array: [0 1 2 3]


In [2]:
# --- 2. Sorting Other Data Types ---
# Alphabetical Sorting

arr_str = np.array(['banana', 'cherry', 'apple'])
print("Alphabetically Sorted:", np.sort(arr_str))

# Boolean Sorting (False comes before True)

arr_bool = np.array([True, False, True])
print("Sorted Booleans:", np.sort(arr_bool))

Alphabetically Sorted: ['apple' 'banana' 'cherry']
Sorted Booleans: [False  True  True]


In [3]:
# --- 3. Sorting 2-D Arrays (Matrices) ---
# Each row is sorted independently

arr_2d = np.array([[3, 2, 4], [5, 0, 1]])
print("Original 2-D Array:\n", arr_2d)
print("Sorted 2-D Array:\n", np.sort(arr_2d))

Original 2-D Array:
 [[3 2 4]
 [5 0 1]]
Sorted 2-D Array:
 [[2 3 4]
 [0 1 5]]


In [4]:
# --- 4. Sorting in Descending Order ---
# NumPy doesn't have a direct 'reverse' parameter in sort, 
# so we use slicing [::-1]

arr_desc = np.array([10, 5, 8, 2])
sorted_desc = np.sort(arr_desc)[::-1]
print("Descending Sort:", sorted_desc)

Descending Sort: [10  8  5  2]
