# 🐍 Python Data Structures — Practice Worksheet
### 18 Tasks covering Numbers, Booleans, Strings, Loops, Lists, Tuples, Dictionaries, Sets, NumPy & Pandas

---

> 📌 **Instructions**
> - Complete **all 18 tasks** from top to bottom — each builds on previous concepts.
> - Fill in every `# YOUR CODE HERE` block. Do **not** change task descriptions.
> - Run each cell after completing it to verify your output.
> - Expected outputs are shown where helpful.

---


## ⚙️ Setup — Run This Cell First


In [1]:
import random
import collections
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
print("All libraries imported successfully ✅")

All libraries imported successfully ✅


---
# 🔢 Section 1 — Primitive Data Types


## 📝 Task 1 — Numbers & Arithmetic

### Background
Python supports two main numeric types: `int` (whole numbers) and `float` (decimals). You can use the standard arithmetic operators: `+`, `-`, `*`, `/`, `//` (floor division), `%` (modulo), `**` (exponentiation).

### 🎯 Your Task
Given `a = 17` and `b = 5`, compute and **print** each of the following with a descriptive label:

| Expression | Expected Output |
|---|---|
| `a + b` | 22 |
| `a - b` | 12 |
| `a * b` | 85 |
| `a / b` | 3.4 |
| `a // b` | 3 |
| `a % b` | 2 |
| `a ** b` | 1419857 |

Then print the **type** of `a` and the **type** of `a / b` and explain (in a comment) why they differ.

> 💡 **Hint:** Use `print(f"a + b = {a + b}")` for clean labelled output. Use `type()` to check types.


In [2]:
a = 17
b = 5

# Print all 7 arithmetic results with labels

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Modulus (Remainder):", a % b)
print("Exponent (Power):", a ** b)
print("Floor Division:", a // b)
print()

# Print type of a

print("Type of a:", type(a))
print()

# Print type of a / b

print("Type of a / b:", type(a / b))
print()

# Comment: why is the type of a/b different from the type of a?
# Answer:
# 'a' is an integer (int), but division using '/' in Python always returns a float.
# Even if the result is a whole number, Python will still represent it as a float.

Addition: 22
Subtraction: 12
Multiplication: 85
Division: 3.4
Modulus (Remainder): 2
Exponent (Power): 1419857
Floor Division: 3

Type of a: <class 'int'>

Type of a / b: <class 'float'>



## 📝 Task 2 — Boolean Logic

### Background
Python's Boolean type has two values: `True` and `False`. Logical operators are written as English words: `and`, `or`, `not`. The XOR (exclusive or) result can be checked with `!=`.

### 🎯 Your Task
Given `p = True` and `q = False`:

1. Print the result of `p and q`, `p or q`, `not p`, and `p != q`
2. Create a variable `score = 73` and write an `if / elif / else` block that prints:
   - `"Distinction"` if score ≥ 85
   - `"Merit"` if score is between 70 and 84 (inclusive)
   - `"Pass"` if score is between 50 and 69 (inclusive)
   - `"Fail"` otherwise

> 💡 **Hint:** Use `elif` for multiple conditions. The order matters — check the highest threshold first.


In [3]:
p = True
q = False

# YOUR CODE HERE — Part 1: Boolean operations

print("p and q:", p and q)
print("p or q:", p or q)
print("not p:", not p)
print("p != q:", p != q)
print()

# YOUR CODE HERE — Part 2: Grade classifier
score = 73
if score >= 85:
    print("Distinction")
elif score >= 70:
    print("Merit")
elif score >= 50:
    print("Pass")
else:
    print("Fail")

p and q: False
p or q: True
not p: False
p != q: True

Merit


## 📝 Task 3 — String Operations

### Background
Strings in Python are sequences of characters. Useful built-in string methods include `.upper()`, `.lower()`, `.replace()`, `.split()`, `.strip()`, and `.count()`. You can also use `len()`, slicing `[start:end]`, and f-strings for formatting.

### 🎯 Your Task
Work with the sentence below and complete all five operations:

```python
sentence = "  Python is a powerful programming language  "
```

| # | Operation | Expected Result |
|---|-----------|-----------------|
| 1 | Strip whitespace | `"Python is a powerful programming language"` |
| 2 | Convert to UPPERCASE | `"PYTHON IS A POWERFUL PROGRAMMING LANGUAGE"` |
| 3 | Count the word `"a"` (exact, case-sensitive) | `1` |
| 4 | Replace `"powerful"` with `"versatile"` | `"Python is a versatile programming language"` |
| 5 | Split into a list of words | `['Python', 'is', 'a', 'versatile', ...]` |

Finally, use an **f-string** to print: `"The sentence has X words."` (where X is the actual count).

> 💡 **Hint:** Chain methods: `sentence.strip().upper()`. Use `.split()` with no arguments to split on any whitespace.


In [4]:
sentence = "  Python is a powerful programming language  "

# YOUR CODE HERE
# 1. Strip whitespace and save to 'clean'

clean = sentence.strip()
print("1. After stripping whitespace:")
print(clean)
print()

# 2. Print UPPERCASE version

print("2. UPPERCASE version:")
print(clean.upper())
print()

# 3. Count occurrences of the word "a"

count_a = clean.split().count("a")
print("3. Count of word 'a':")
print(count_a)
print()

# 4. Replace "powerful" with "versatile" and save to 'new_sentence'

new_sentence = clean.replace("powerful", "versatile")
print("4. After replacing 'powerful' with 'versatile':")
print(new_sentence)
print()

# 5. Split new_sentence into a list of words

words = new_sentence.split()
print("5. List of words:")
print(words)
print()

# Print: "The sentence has X words."

print(f"The sentence has {len(words)} words.")

1. After stripping whitespace:
Python is a powerful programming language

2. UPPERCASE version:
PYTHON IS A POWERFUL PROGRAMMING LANGUAGE

3. Count of word 'a':
1

4. After replacing 'powerful' with 'versatile':
Python is a versatile programming language

5. List of words:
['Python', 'is', 'a', 'versatile', 'programming', 'language']

The sentence has 6 words.


## 📝 Task 4 — Loops & Conditionals

### Background
`for` loops iterate over a sequence. `while` loops run as long as a condition is `True`. Use `break` to exit early and `continue` to skip to the next iteration.

### 🎯 Your Task

**Part A:** Use a `for` loop with `range()` to print all **even numbers from 1 to 30** on a single line separated by spaces.

**Part B:** Use a `while` loop to compute the **sum of all odd numbers from 1 to 99** (i.e., 1 + 3 + 5 + … + 99). Print the result.
> Expected answer: 2500

**Part C:** Use a `for` loop over `range(1, 21)`. Print the number normally, **but**:
- If divisible by both 3 and 5 → print `"FizzBuzz"`
- If divisible by 3 only → print `"Fizz"`
- If divisible by 5 only → print `"Buzz"`

> 💡 **Hint for Part A:** Use `print(n, end=' ')` to stay on the same line, or build a list and use `' '.join(...)`.  
> 💡 **Hint for Part C:** Check the combined condition (`% 3 == 0 and % 5 == 0`) **first** before the individual ones.


In [5]:
# Part A: Even numbers from 1 to 30
# YOUR CODE HERE

print("Part A: Even numbers from 1 to 30:")
for n in range(1, 31):
    if n % 2 == 0:
        print(n, end=' ')
print("\n")

# Part B: Sum of odd numbers from 1 to 99
# YOUR CODE HERE

print("Part B: Sum of odd numbers from 1 to 99:")

sum_odd = 0
i = 1

while i <= 99:
    if i % 2 != 0:
        sum_odd += i
    i += 1

print("Sum:", sum_odd)
print()

# Part C: FizzBuzz from 1 to 20
# YOUR CODE HERE

print("Part C: FizzBuzz from 1 to 20:")

for n in range(1, 21):
    if n % 3 == 0 and n % 5 == 0:
        print("FizzBuzz")
    elif n % 3 == 0:
        print("Fizz")
    elif n % 5 == 0:
        print("Buzz")
    else:
        print(n)

Part A: Even numbers from 1 to 30:
2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 

Part B: Sum of odd numbers from 1 to 99:
Sum: 2500

Part C: FizzBuzz from 1 to 20:
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz


---
# 📋 Section 2 — Lists


## 📝 Task 5 — List Basics: Create, Access, Modify

### Background
A Python list is **mutable** and **ordered**. Elements are accessed by zero-based index. Negative indices count from the end (`-1` is the last element). Common methods: `.append()`, `.insert()`, `.remove()`, `.pop()`, `.sort()`, `.reverse()`.

### 🎯 Your Task
Start with:
```python
fruits = ["mango", "banana", "apple", "cherry", "orange"]
```

Perform the following operations **in order**, printing the list after each step:

1. Print the **first** and **last** element using positive and negative indexing.
2. **Append** `"grape"` to the end.
3. **Insert** `"kiwi"` at index 2.
4. **Remove** `"banana"` from the list.
5. **Pop** the element at index 0 and print what was removed.
6. **Sort** the list alphabetically and print it.
7. **Reverse** the sorted list and print it.

> 💡 **Hint:** Remember that `.pop(index)` returns the removed element, so you can capture it: `removed = fruits.pop(0)`.


In [6]:
fruits = ["mango", "banana", "apple", "cherry", "orange"]

# YOUR CODE HERE
# 1. Print first and last elements

print("1. First and Last elements:")
print("First:", fruits[0])
print("Last:", fruits[-1])
print()

# 2. Append "grape"

fruits.append("grape")
print("2. After appending 'grape':")
print(fruits)
print()

# 3. Insert "kiwi" at index 2

fruits.insert(2, "kiwi")
print("3. After inserting 'kiwi' at index 2:")
print(fruits)
print()

# 4. Remove "banana"

fruits.remove("banana")
print("4. After removing 'banana':")
print(fruits)
print()

# 5. Pop element at index 0, print what was removed

removed_item = fruits.pop(0)
print("5. After popping index 0:")
print("Removed item:", removed_item)
print("Updated list:", fruits)
print()

# 6. Sort alphabetically

fruits.sort()
print("6. After sorting alphabetically:")
print(fruits)
print()

# 7. Reverse the list

fruits.reverse()
print("7. After reversing the list:")
print(fruits)

1. First and Last elements:
First: mango
Last: orange

2. After appending 'grape':
['mango', 'banana', 'apple', 'cherry', 'orange', 'grape']

3. After inserting 'kiwi' at index 2:
['mango', 'banana', 'kiwi', 'apple', 'cherry', 'orange', 'grape']

4. After removing 'banana':
['mango', 'kiwi', 'apple', 'cherry', 'orange', 'grape']

5. After popping index 0:
Removed item: mango
Updated list: ['kiwi', 'apple', 'cherry', 'orange', 'grape']

6. After sorting alphabetically:
['apple', 'cherry', 'grape', 'kiwi', 'orange']

7. After reversing the list:
['orange', 'kiwi', 'grape', 'cherry', 'apple']


## 📝 Task 6 — List Slicing

### Background
Slicing extracts a **sub-list** using the syntax `list[start:stop:step]`:
- `start` is inclusive, `stop` is exclusive
- A negative `step` reverses the direction
- Omitting `start` or `stop` defaults to the beginning or end

### 🎯 Your Task
Work with:
```python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

| # | Slice | Expected Result |
|---|-------|-----------------|
| 1 | First 4 elements | `[0, 1, 2, 3]` |
| 2 | Last 3 elements | `[7, 8, 9]` |
| 3 | Elements from index 2 to 7 | `[2, 3, 4, 5, 6]` |
| 4 | Every second element | `[0, 2, 4, 6, 8]` |
| 5 | The entire list **reversed** | `[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]` |
| 6 | Last 5 elements **reversed** | `[9, 8, 7, 6, 5]` |

> 💡 **Hint:** To reverse use `[::-1]`. For last N items use `[-N:]`. To reverse a slice: `numbers[4:9][::-1]` reverses a sub-section.


In [7]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# YOUR CODE HERE
# 1. First 4 elements

print("1. First 4 elements:")
print(numbers[:4])
print()

# 2. Last 3 elements

print("2. Last 3 elements:")
print(numbers[-3:])
print()

# 3. Index 2 to 7 (not including 7)

print("3. Elements from index 2 to 7:")
print(numbers[2:7])
print()

# 4. Every second element

print("4. Every second element:")
print(numbers[::2])
print()

# 5. Entire list reversed

print("5. Entire list reversed:")
print(numbers[::-1])
print()

# 6. Last 5 elements reversed

print("6. Last 5 elements reversed:")
print(numbers[-5:][::-1])

1. First 4 elements:
[0, 1, 2, 3]

2. Last 3 elements:
[7, 8, 9]

3. Elements from index 2 to 7:
[2, 3, 4, 5, 6]

4. Every second element:
[0, 2, 4, 6, 8]

5. Entire list reversed:
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

6. Last 5 elements reversed:
[9, 8, 7, 6, 5]


## 📝 Task 7 — List Comprehensions

### Background
List comprehensions are a concise way to create lists:
```python
[expression for item in iterable if condition]
```
They replace many `for` loops with a single readable line.

### 🎯 Your Task
Use **list comprehensions** (no regular for-loops!) to create and print each of the following:

1. A list of the **squares** of numbers 1 through 15: `[1, 4, 9, 16, ...]`
2. A list of numbers from 1–50 that are **divisible by 3 or 5** (but not both): `[3, 5, 6, 9, 10, ...]`
3. A list of the **lengths** of each word in the sentence `"the quick brown fox jumps over the lazy dog"`
4. A list of **uppercase versions** of only the words that have **5 or more letters**: `['QUICK', 'BROWN', 'JUMPS', 'LAZY']` *(hint: 'over' has 4, skip it)*

> 💡 **Hint for #2:** `(n % 3 == 0) != (n % 5 == 0)` is Python's way to express XOR for two conditions.  
> 💡 **Hint for #3:** `sentence.split()` gives you the word list.


In [8]:
# 1. Squares of 1 to 15
# YOUR CODE HERE

squares = [n**2 for n in range(1, 16)]
print("1. Squares of numbers 1 to 15:")
print(squares)
print()

# 2. Numbers 1-50 divisible by 3 OR 5 but NOT both
# YOUR CODE HERE

nums = [n for n in range(1, 51) if (n % 3 == 0) != (n % 5 == 0)]
print("2. Numbers divisible by 3 or 5 but NOT both:")
print(nums)
print()

# 3. Lengths of each word in the sentence
sentence = "the quick brown fox jumps over the lazy dog"
# YOUR CODE HERE

sentence = "the quick brown fox jumps over the lazy dog"
lengths = [len(word) for word in sentence.split()]
print("3. Length of each word:")
print(lengths)
print()

# 4. Uppercase words with 5 or more letters
# YOUR CODE HERE

upper_words = [word.upper() for word in sentence.split() if len(word) >= 5]
print("4. Uppercase words with 5 or more letters:")
print(upper_words)
print()

1. Squares of numbers 1 to 15:
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225]

2. Numbers divisible by 3 or 5 but NOT both:
[3, 5, 6, 9, 10, 12, 18, 20, 21, 24, 25, 27, 33, 35, 36, 39, 40, 42, 48, 50]

3. Length of each word:
[3, 5, 5, 3, 5, 4, 3, 4, 3]

4. Uppercase words with 5 or more letters:
['QUICK', 'BROWN', 'JUMPS']



## 📝 Task 8 — Nested Lists & the `collections.Counter`

### Background
A **list of lists** creates a 2D (matrix-like) structure. Access elements with `matrix[row][col]`.  
`collections.Counter` is a dictionary subclass that counts how many times each element appears in an iterable.

### 🎯 Your Task

**Part A — Nested List:**  
Create the following 3×3 matrix as a list of lists and then:
```
matrix = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]
```
- Print the **second row** (index 1)
- Print the **element at row 2, column 1** (value: 8)
- Use a nested list comprehension to create a **transposed** version (rows become columns)
  - Expected: `[[1, 4, 7], [2, 5, 8], [3, 6, 9]]`

**Part B — Counter:**  
Generate a list of 300 random integers between 1 and 10 (inclusive), then:
- Use `collections.Counter` to count each number
- Print the **3 most common** numbers and their counts
- Print the **least common** number

> 💡 **Hint for transpose:** `[[matrix[r][c] for r in range(3)] for c in range(3)]`  
> 💡 **Hint for Counter:** `counter.most_common(3)` returns the top 3 as a list of `(value, count)` tuples.


In [9]:
import collections, random
from collections import Counter

# Part A — Nested list
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# YOUR CODE HERE
# Print second row

print("Part A - 1. Second row (index 1):")
print(matrix[1])
print()

# Print element at row 2, col 1

print("Part A - 2. Element at row 2, col 1:")
print(matrix[2][1])
print()

# Transpose using nested list comprehension

transpose = [[matrix[r][c] for r in range(3)] for c in range(3)]
print("Part A - 3. Transposed matrix:")
print(transpose)
print()

# Part B — Counter
random.seed(42)
# YOUR CODE HERE
# Generate 300 random integers between 1 and 10

numbers = [random.randint(1, 10) for _ in range(300)]
print("Part B - 1. Sample of first 20 random numbers:")
print(numbers[:20])  # just to verify
print()

# Count with Counter

counter = Counter(numbers)
print("Part B - 2. Full counts:")
print(counter)
print()

# Print top 3 most common

top3 = counter.most_common(3)
print("Part B - 3. Top 3 most common numbers:")
print(top3)
print()

# Print least common

min_count = min(counter.values())
least_common = [num for num, cnt in counter.items() if cnt == min_count]
print("Part B - 4. Least common number(s):")
print(least_common)

Part A - 1. Second row (index 1):
[4, 5, 6]

Part A - 2. Element at row 2, col 1:
8

Part A - 3. Transposed matrix:
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

Part B - 1. Sample of first 20 random numbers:
[2, 1, 5, 4, 4, 3, 2, 9, 2, 10, 7, 1, 1, 2, 4, 4, 9, 10, 1, 9]

Part B - 2. Full counts:
Counter({4: 42, 2: 40, 9: 35, 1: 30, 7: 29, 3: 26, 8: 26, 5: 25, 10: 25, 6: 22})

Part B - 3. Top 3 most common numbers:
[(4, 42), (2, 40), (9, 35)]

Part B - 4. Least common number(s):
[6]


---
# 🔒 Section 3 — Tuples


In [10]:
# Part A
student = ("Alice", 22, "Computer Science", 3.8)

# YOUR CODE HERE
# Print name and GPA

print("Step 1: Student's name and GPA")
print("Name:", student[0])
print("GPA:", student[3])
print()

# Try to change name — catch TypeError

print("Step 2: Attempt to change name")
try:
    student[0] = "Bob"
except TypeError:
    print("Tuples are immutable!")
print()

# Unpack into 4 variables and print each

print("Step 3: Unpacking tuple into variables")
name, age, major, gpa = student
print("Name:", name)
print("Age:", age)
print("Major:", major)
print("GPA:", gpa)
print()

# Part B
cities = [("Karachi",   24.86, 67.01),
          ("Lahore",    31.55, 74.35),
          ("Islamabad", 33.72, 73.06),
          ("Peshawar",  34.01, 71.57),
          ("Quetta",    30.18, 66.99)]

# YOUR CODE HERE
# Loop and print each city's info

print("Step 1: Printing each city's info")
for city in cities:
    print(f"City: {city[0]} | Lat: {city[1]} | Lon: {city[2]}")
print()

# Sort by latitude and print

print("Step 2: Cities sorted by latitude")
sorted_cities = sorted(cities, key=lambda c: c[1])
for city in sorted_cities:
    print(f"City: {city[0]} | Lat: {city[1]} | Lon: {city[2]}")
print()

Step 1: Student's name and GPA
Name: Alice
GPA: 3.8

Step 2: Attempt to change name
Tuples are immutable!

Step 3: Unpacking tuple into variables
Name: Alice
Age: 22
Major: Computer Science
GPA: 3.8

Step 1: Printing each city's info
City: Karachi | Lat: 24.86 | Lon: 67.01
City: Lahore | Lat: 31.55 | Lon: 74.35
City: Islamabad | Lat: 33.72 | Lon: 73.06
City: Peshawar | Lat: 34.01 | Lon: 71.57
City: Quetta | Lat: 30.18 | Lon: 66.99

Step 2: Cities sorted by latitude
City: Karachi | Lat: 24.86 | Lon: 67.01
City: Quetta | Lat: 30.18 | Lon: 66.99
City: Lahore | Lat: 31.55 | Lon: 74.35
City: Islamabad | Lat: 33.72 | Lon: 73.06
City: Peshawar | Lat: 34.01 | Lon: 71.57



---
# 📖 Section 4 — Dictionaries


## 📝 Task 10 — Dictionary Basics: Create, Access, Update

### Background
A dictionary stores data as **key → value** pairs. Keys must be unique and immutable (strings, numbers, tuples). Values can be anything. Key methods: `.keys()`, `.values()`, `.items()`, `.get()`, `.update()`, `.pop()`.

### 🎯 Your Task
Start with this student record:
```python
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}
```

1. Print Sara's **name** and **age**
2. Print her **list of courses**
3. Print her **CS grade** (access the nested dictionary)
4. Add a new key `"year"` with value `2`
5. Update her **age** to `21`
6. Remove the `"Physics"` grade from the nested `"grades"` dictionary using `.pop()`
7. Loop over all key-value pairs with `.items()` and print them line by line
8. Print a list of all **keys** and a list of all **values**

> 💡 **Hint:** Access nested dicts with chained brackets: `student["grades"]["CS"]`  
> 💡 **Hint:** `student.get("email", "Not found")` returns a default value if the key doesn't exist.


In [11]:
student = {
    "name": "Sara",
    "age": 20,
    "courses": ["Math", "Physics", "CS"],
    "grades": {"Math": 88, "Physics": 75, "CS": 92}
}

# YOUR CODE HERE
# 1. Print name and age

print("Step 1: Student's name and age")
print("Name:", student["name"])
print("Age:", student["age"])
print()

# 2. Print list of courses

print("Step 2: List of courses")
print(student["courses"])
print()

# 3. Print CS grade (nested access)

print("Step 3: CS grade")
print("CS Grade:", student["grades"]["CS"])
print()

# 4. Add "year": 2

student["year"] = 2
print("Step 4: Added year")
print(student)
print()

# 5. Update age to 21

print("Step 5: Update age to 21")
student["age"] = 21
print(student)
print()

# 6. Remove "Physics" from grades using .pop()

print("Step 6: Remove Physics grade")
removed_grade = student["grades"].pop("Physics")
print("Removed Physics grade:", removed_grade)
print("Updated grades:", student["grades"])
print()

# 7. Loop and print all key-value pairs

print("Step 7: Loop over all key-value pairs")
for key, value in student.items():
    print(f"{key}: {value}")
print()

# 8. Print list of keys and list of values

print("Step 8: List of keys and values")
print("Keys:", list(student.keys()))
print("Values:", list(student.values()))
print()

Step 1: Student's name and age
Name: Sara
Age: 20

Step 2: List of courses
['Math', 'Physics', 'CS']

Step 3: CS grade
CS Grade: 92

Step 4: Added year
{'name': 'Sara', 'age': 20, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'Physics': 75, 'CS': 92}, 'year': 2}

Step 5: Update age to 21
{'name': 'Sara', 'age': 21, 'courses': ['Math', 'Physics', 'CS'], 'grades': {'Math': 88, 'Physics': 75, 'CS': 92}, 'year': 2}

Step 6: Remove Physics grade
Removed Physics grade: 75
Updated grades: {'Math': 88, 'CS': 92}

Step 7: Loop over all key-value pairs
name: Sara
age: 21
courses: ['Math', 'Physics', 'CS']
grades: {'Math': 88, 'CS': 92}
year: 2

Step 8: List of keys and values
Keys: ['name', 'age', 'courses', 'grades', 'year']
Values: ['Sara', 21, ['Math', 'Physics', 'CS'], {'Math': 88, 'CS': 92}, 2]




## 📝 Task 11 — Dictionary Comprehension & Word Frequency Counter

### Background
Just like list comprehensions, you can build dictionaries in one line:
```python
{key_expr: value_expr for item in iterable if condition}
```
Dictionaries are perfect for counting frequencies — a pattern you'll use constantly in data science.

### 🎯 Your Task

**Part A — Dictionary Comprehension:**
1. Create a dictionary mapping each number 1–10 to its **cube**: `{1: 1, 2: 8, 3: 27, ...}`
2. Create a dictionary mapping each number 1–20 to `"even"` or `"odd"`: `{1: 'odd', 2: 'even', ...}`

**Part B — Word Frequency Counter:**  
Count how many times each word appears in the text below, ignoring case. Print the result sorted by **frequency (descending)**.

```python
text = "to be or not to be that is the question to be is to think"
```
Expected top entries: `to: 4, be: 3, is: 2, ...`

> 💡 **Hint for Part B:** Start with `freq = {}`, then loop over `text.lower().split()`.  
> Use `freq[word] = freq.get(word, 0) + 1` to safely increment counts.  
> Sort with `sorted(freq.items(), key=lambda x: x[1], reverse=True)`.


In [12]:
# Part A — Dictionary comprehensions
# 1. Cubes of 1 to 10
# YOUR CODE HERE

print("Step 1: Cubes of numbers 1 to 10")
cubes = {i: i**3 for i in range(1, 11)}
print(cubes)
print()

# 2. Even/Odd mapping for 1 to 20
# YOUR CODE HERE

even_odd = {i: ("even" if i % 2 == 0 else "odd") for i in range(1, 21)}

print("Step 2: Even/Odd mapping")
print(even_odd)
print()

# Part B — Word frequency counter
text = "to be or not to be that is the question to be is to think"
# YOUR CODE HERE

print("Step 3: Word frequency counter (ignoring case)")
text = "to be or not to be that is the question to be is to think"

freq = {}
for word in text.lower().split():
    freq[word] = freq.get(word, 0) + 1

sorted_freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)

for word, count in sorted_freq:
    print(f"{word}: {count}")
print()

Step 1: Cubes of numbers 1 to 10
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}

Step 2: Even/Odd mapping
{1: 'odd', 2: 'even', 3: 'odd', 4: 'even', 5: 'odd', 6: 'even', 7: 'odd', 8: 'even', 9: 'odd', 10: 'even', 11: 'odd', 12: 'even', 13: 'odd', 14: 'even', 15: 'odd', 16: 'even', 17: 'odd', 18: 'even', 19: 'odd', 20: 'even'}

Step 3: Word frequency counter (ignoring case)
to: 4
be: 3
is: 2
or: 1
not: 1
that: 1
the: 1
question: 1
think: 1



---
# 🔵 Section 5 — Sets


## 📝 Task 12 — Set Operations

### Background
A **set** is an **unordered collection of unique elements**. Duplicate values are automatically removed. Sets support mathematical operations: union (`|`), intersection (`&`), difference (`-`), symmetric difference (`^`).

| Operation | Symbol | Method | Meaning |
|-----------|--------|--------|---------|
| Union | `\|` | `.union()` | All elements from both sets |
| Intersection | `&` | `.intersection()` | Only elements in **both** |
| Difference | `-` | `.difference()` | Elements in A but **not** B |
| Symmetric Difference | `^` | `.symmetric_difference()` | Elements in either but **not both** |

### 🎯 Your Task
```python
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}
```

1. Find students enrolled in **both** courses (intersection)
2. Find students enrolled in **at least one** course (union)
3. Find students taking **Python but NOT Java** (difference)
4. Find students taking **exactly one** course (symmetric difference)
5. Check if `{"Bob", "Alice"}` is a **subset** of `python_students`
6. Add `"Henry"` to `python_students` and remove `"Carol"` from it
7. Create a list `[1, 2, 2, 3, 3, 3, 4, 4, 4, 4]` and use a set to print only the **unique values**

> 💡 **Hint:** Use `.issubset()` or the `<=` operator for subset check.


In [13]:
python_students = {"Alice", "Bob", "Carol", "David", "Eve"}
java_students   = {"Bob", "David", "Frank", "Grace", "Alice"}

# YOUR CODE HERE
# 1. Intersection

print("Step 1: Students in both Python and Java (intersection)")
both_courses = python_students & java_students
print(both_courses)
print()

# 2. Union

print("Step 2: Students in at least one course (union)")
all_students = python_students | java_students
print(all_students)
print()

# 3. Difference (Python but NOT Java)

print("Step 3: Students taking Python but NOT Java (difference)")
python_only = python_students - java_students
print(python_only)
print()

# 4. Symmetric difference

print("Step 4: Students taking exactly one course (symmetric difference)")
one_course = python_students ^ java_students
print(one_course)
print()

# 5. Subset check: {"Bob", "Alice"} ⊆ python_students

print("Step 5: Check if {'Bob', 'Alice'} is subset of python_students")
subset_check = {"Bob", "Alice"} <= python_students
print(subset_check)
print()

# 6. Add "Henry", remove "Carol"

print("Step 6: Add 'Henry' and remove 'Carol'")
python_students.add("Henry")
python_students.discard("Carol") 
print(python_students)
print()

# 7. Unique values from list

print("Step 7: Unique values from a list using set")
nums = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
unique_nums = set(nums)
print(unique_nums)
print()

Step 1: Students in both Python and Java (intersection)
{'Bob', 'Alice', 'David'}

Step 2: Students in at least one course (union)
{'Alice', 'Frank', 'Grace', 'Eve', 'Carol', 'David', 'Bob'}

Step 3: Students taking Python but NOT Java (difference)
{'Carol', 'Eve'}

Step 4: Students taking exactly one course (symmetric difference)
{'Grace', 'Eve', 'Carol', 'Frank'}

Step 5: Check if {'Bob', 'Alice'} is subset of python_students
True

Step 6: Add 'Henry' and remove 'Carol'
{'Bob', 'Alice', 'Eve', 'David', 'Henry'}

Step 7: Unique values from a list using set
{1, 2, 3, 4}



---
# 🔢 Section 6 — NumPy Arrays


## 📝 Task 13 — Creating & Inspecting NumPy Arrays

### Background
NumPy arrays are **fixed-type, multi-dimensional** arrays that support fast vectorised operations. Unlike Python lists, every element must be the same type. Key creation functions: `np.array()`, `np.arange()`, `np.linspace()`, `np.zeros()`, `np.ones()`, `np.eye()`, `np.random.random()`.

### 🎯 Your Task

Create each of the following arrays and print both the array and its `.shape` and `.dtype`:

| # | Function | Parameters | Expected shape |
|---|----------|------------|----------------|
| 1 | `np.arange` | 0 to 20, step 2 | `(11,)` |
| 2 | `np.linspace` | 0 to 1, 6 evenly spaced points | `(6,)` |
| 3 | `np.zeros` | 3 rows × 4 columns | `(3, 4)` |
| 4 | `np.ones` | 2 rows × 5 columns, dtype `int16` | `(2, 5)` |
| 5 | `np.eye` | 4×4 identity matrix | `(4, 4)` |
| 6 | `np.random.randint` | values 1–100, shape 3×3 | `(3, 3)` |

> 💡 **Hint:** `np.ones((2,5), dtype='int16')` creates an integer array of ones.  
> `np.random.randint(low, high, size=(r,c))` creates random integer arrays.


In [14]:
import numpy as np

# YOUR CODE HERE
# 1. arange: 0 to 20 step 2

print("Step 1: np.arange from 0 to 20, step 2")
arr1 = np.arange(0, 21, 2)
print("Array:\n", arr1)
print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)
print()

# 2. linspace: 0 to 1 with 6 points

print("Step 2: np.linspace from 0 to 1 with 6 points")
arr2 = np.linspace(0, 1, 6)
print("Array:\n", arr2)
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)
print()

# 3. zeros: 3x4

print("Step 3: np.zeros 3x4")
arr3 = np.zeros((3, 4))
print("Array:\n", arr3)
print("Shape:", arr3.shape)
print("Dtype:", arr3.dtype)
print()

# 4. ones: 2x5 dtype int16

print("Step 4: np.ones 2x5, dtype=int16")
arr4 = np.ones((2, 5), dtype='int16')
print("Array:\n", arr4)
print("Shape:", arr4.shape)
print("Dtype:", arr4.dtype)
print()

# 5. eye: 4x4 identity

print("Step 5: np.eye 4x4 identity")
arr5 = np.eye(4)
print("Array:\n", arr5)
print("Shape:", arr5.shape)
print("Dtype:", arr5.dtype)
print()

# 6. random integers 1-100, shape 3x3

print("Step 6: np.random.randint 1-100, shape 3x3")
arr6 = np.random.randint(1, 101, size=(3, 3))
print("Array:\n", arr6)
print("Shape:", arr6.shape)
print("Dtype:", arr6.dtype)
print()

Step 1: np.arange from 0 to 20, step 2
Array:
 [ 0  2  4  6  8 10 12 14 16 18 20]
Shape: (11,)
Dtype: int64

Step 2: np.linspace from 0 to 1 with 6 points
Array:
 [0.  0.2 0.4 0.6 0.8 1. ]
Shape: (6,)
Dtype: float64

Step 3: np.zeros 3x4
Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Dtype: float64

Step 4: np.ones 2x5, dtype=int16
Array:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (2, 5)
Dtype: int16

Step 5: np.eye 4x4 identity
Array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape: (4, 4)
Dtype: float64

Step 6: np.random.randint 1-100, shape 3x3
Array:
 [[24 53 45]
 [76 12 98]
 [92  2 20]]
Shape: (3, 3)
Dtype: int32



## 📝 Task 14 — Array Indexing, Slicing & Reshaping

### Background
NumPy arrays use **row, column** indexing: `A[row, col]` or `A[row][col]`.  
Slicing: `A[r1:r2, c1:c2]` extracts a sub-array.  
`.reshape(rows, cols)` changes the shape without changing the data.  
`.T` gives the transpose.

### 🎯 Your Task
```python
A = np.arange(1, 26).reshape(5, 5)
```
This creates:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
```

1. Print the **element at row 2, column 3** (value: 14)
2. Print the **entire third row** (index 2): `[11 12 13 14 15]`
3. Print the **entire second column** (index 1): `[ 2  7 12 17 22]`
4. Extract the **top-left 3×3 sub-matrix**: rows 0–2, columns 0–2
5. Extract the **bottom-right 2×2 sub-matrix**: last 2 rows and last 2 cols
6. Print the **transpose** of A (shape should become `(5,5)` but rows/cols swapped)
7. Reshape A into a 1D array of 25 elements, then into a shape `(25, 1)` column vector

> 💡 **Hint:** `A[:3, :3]` extracts the top-left corner. `A[-2:, -2:]` grabs the bottom-right corner.


In [15]:
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
print("Original matrix A:")
print(A)
print()

# YOUR CODE HERE
# 1. Element at row 2, col 3

print("Step 1: Element at row 2, column 3")
elem = A[2, 3]
print(elem)
print()

# 2. Entire third row (index 2)

print("Step 2: Entire third row (index 2)")
third_row = A[2, :]
print(third_row)
print()

# 3. Entire second column (index 1)

print("Step 3: Entire second column (index 1)")
second_col = A[:, 1]
print(second_col)
print()

# 4. Top-left 3x3 sub-matrix

print("Step 4: Top-left 3x3 sub-matrix")
top_left = A[:3, :3]
print(top_left)
print()

# 5. Bottom-right 2x2 sub-matrix

print("Step 5: Bottom-right 2x2 sub-matrix")
bottom_right = A[-2:, -2:]
print(bottom_right)
print()

# 6. Transpose

print("Step 6: Transpose of A")
A_T = A.T
print(A_T)
print("Shape:", A_T.shape)
print()

# 7. Reshape to 1D (25,) then to column vector (25,1)

print("Step 7: Reshape to 1D array and column vector")
A_1D = A.reshape(-1)
print("1D array:", A_1D)
A_col = A.reshape(25, 1)
print("Column vector (25,1):\n", A_col)

Original matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Step 1: Element at row 2, column 3
14

Step 2: Entire third row (index 2)
[11 12 13 14 15]

Step 3: Entire second column (index 1)
[ 2  7 12 17 22]

Step 4: Top-left 3x3 sub-matrix
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]

Step 5: Bottom-right 2x2 sub-matrix
[[19 20]
 [24 25]]

Step 6: Transpose of A
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
Shape: (5, 5)

Step 7: Reshape to 1D array and column vector
1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Column vector (25,1):
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]


## 📝 Task 15 — Vectorised Operations & Broadcasting

### Background
NumPy operations are applied **element-wise** to entire arrays without writing loops — this is called **vectorisation**. When arrays have compatible shapes, NumPy can **broadcast** smaller arrays across larger ones automatically.

### 🎯 Your Task

**Part A — Element-wise Operations:**
```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])
```
Compute and print (without loops):
1. `a + b`, `a - b`, `a * b`, `a / b`
2. Square root of `a` (use `np.sqrt`)
3. All elements of `a` greater than 25 (Boolean mask)
4. Use the Boolean mask to extract only elements of `a` greater than 25

**Part B — Matrix Operations:**
```python
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])
```
5. Element-wise multiplication `M * N`
6. Matrix (dot) product `M @ N` or `np.dot(M, N)`
7. Sum of all elements, sum along each row, sum along each column

> 💡 **Hint for Boolean masking:** `mask = a > 25` creates `[False False False True True]`. Then `a[mask]` extracts `[40 50]`.  
> 💡 **Hint for axis sums:** `M.sum(axis=1)` sums each row; `M.sum(axis=0)` sums each column.


In [16]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([ 1,  2,  3,  4,  5])

# Part A
# YOUR CODE HERE
# 1. Element-wise +, -, *, /

print("Step 1: Element-wise operations")
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print()

# 2. Square root of a

print("Step 2: Square root of a")
sqrt_a = np.sqrt(a)
print("np.sqrt(a) =", sqrt_a)
print()

# 3. Boolean mask: elements of a > 25

print("Step 3: Boolean mask for a > 25")
mask = a > 25
print("mask =", mask)
print()

# 4. Extract elements > 25 using mask

print("Step 4: Elements of a > 25")
filtered_a = a[mask]
print("filtered_a =", filtered_a)
print()

# Part B
M = np.array([[1, 2], [3, 4]])
N = np.array([[5, 6], [7, 8]])

# YOUR CODE HERE
# 5. Element-wise multiplication

print("Step 5: Element-wise multiplication M * N")
elementwise_mult = M * N
print("M * N =", elementwise_mult)
print()

# 6. Matrix dot product

print("Step 6: Matrix dot product M @ N")
dot_product = M @ N  # or np.dot(M, N)
print("M @ N =", dot_product)
print()

# 7. Total sum, row sums, column sums

print("Step 7: Sum operations")
total_sum = M.sum()
row_sums = M.sum(axis=1)
col_sums = M.sum(axis=0)
print("Total sum of M =", total_sum)
print("Sum of each row =", row_sums)
print("Sum of each column =", col_sums)

Step 1: Element-wise operations
a + b = [11 22 33 44 55]
a - b = [ 9 18 27 36 45]
a * b = [ 10  40  90 160 250]
a / b = [10. 10. 10. 10. 10.]

Step 2: Square root of a
np.sqrt(a) = [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Step 3: Boolean mask for a > 25
mask = [False False  True  True  True]

Step 4: Elements of a > 25
filtered_a = [30 40 50]

Step 5: Element-wise multiplication M * N
M * N = [[ 5 12]
 [21 32]]

Step 6: Matrix dot product M @ N
M @ N = [[19 22]
 [43 50]]

Step 7: Sum operations
Total sum of M = 10
Sum of each row = [3 7]
Sum of each column = [4 6]


---
# 🐼 Section 7 — Pandas DataFrames


## 📝 Task 16 — Creating & Exploring a DataFrame

### Background
A **DataFrame** is a 2D table with labelled rows (index) and columns. You can create one from a dictionary, a list of lists, a CSV file, or from scikit-learn datasets. Essential inspection methods: `.head()`, `.tail()`, `.info()`, `.describe()`, `.shape`, `.columns`, `.dtypes`, `.isnull().sum()`.

### 🎯 Your Task

**Part A — Create from a dictionary:**
```python
data = {
    "Name":    ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":     [23, 21, 25, 22, 24],
    "Score":   [88, 92, 78, 95, 83],
    "Passed":  [True, True, True, True, True],
    "City":    ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}
```
1. Create a DataFrame from this dictionary
2. Print its **shape**, **column names**, and **data types**
3. Print the **first 3 rows** and the **last 2 rows**
4. Print **summary statistics** using `.describe()`

**Part B — Load the Iris dataset:**
5. Load the Iris dataset using `load_iris()` and add the species names
6. Print **how many rows belong to each species** using `.value_counts()`
7. Print the **mean of each numerical column grouped by species**

> 💡 **Hint for Iris:** `iris_df['species'] = iris.target_names[iris.target]` maps integer targets to names.  
> 💡 **Hint for groupby:** `iris_df.groupby('species').mean(numeric_only=True)`


In [17]:
import pandas as pd
from sklearn.datasets import load_iris

# Part A
data = {
    "Name":   ["Ali", "Sara", "John", "Fatima", "Chris"],
    "Age":    [23, 21, 25, 22, 24],
    "Score":  [88, 92, 78, 95, 83],
    "Passed": [True, True, True, True, True],
    "City":   ["Lahore", "Karachi", "London", "Islamabad", "New York"]
}

# YOUR CODE HERE
# 1. Create DataFrame

df = pd.DataFrame(data)
print("Step 1: DataFrame created")
print(df)
print()

# 2. Print shape, columns, dtypes

print("Step 2: Shape, columns, dtypes")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data types:\n", df.dtypes)
print()

# 3. Head(3) and tail(2)

print("Step 3: Head(3) and Tail(2)")
print("First 3 rows:\n", df.head(3))
print("Last 2 rows:\n", df.tail(2))
print()

# 4. Describe

print("Step 4: Summary statistics")
print(df.describe())
print()

# Part B — Iris
# YOUR CODE HERE
# 5. Load iris and create DataFrame

iris = load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target] 
print("Step 5: First 5 rows of Iris DataFrame")
print(iris_df.head())
print()

# 6. Value counts per species

print("Step 6: Number of rows per species")
print(iris_df['species'].value_counts())
print()

# 7. Mean per species

print("Step 7: Mean per species")
print(iris_df.groupby('species').mean(numeric_only=True))

Step 1: DataFrame created
     Name  Age  Score  Passed       City
0     Ali   23     88    True     Lahore
1    Sara   21     92    True    Karachi
2    John   25     78    True     London
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York

Step 2: Shape, columns, dtypes
Shape: (5, 5)
Columns: ['Name', 'Age', 'Score', 'Passed', 'City']
Data types:
 Name      object
Age        int64
Score      int64
Passed      bool
City      object
dtype: object

Step 3: Head(3) and Tail(2)
First 3 rows:
    Name  Age  Score  Passed     City
0   Ali   23     88    True   Lahore
1  Sara   21     92    True  Karachi
2  John   25     78    True   London
Last 2 rows:
      Name  Age  Score  Passed       City
3  Fatima   22     95    True  Islamabad
4   Chris   24     83    True   New York

Step 4: Summary statistics
             Age     Score
count   5.000000   5.00000
mean   23.000000  87.20000
std     1.581139   6.83374
min    21.000000  78.00000
25%    22.000000  83.00000

## 📝 Task 17 — Selecting, Filtering & Adding Columns

### Background
- **Select columns:** `df['col']` (Series) or `df[['col1','col2']]` (DataFrame)
- **Select rows by position:** `df.iloc[start:stop]`
- **Select rows by label/condition:** `df.loc[condition]`
- **Add a column:** `df['new_col'] = expression`
- **Multiple conditions:** Use `&` (AND) or `|` (OR) — wrap each condition in `()`

### 🎯 Your Task
Use the **Iris DataFrame** from Task 16.

1. Select and print only the `sepal length (cm)` and `petal length (cm)` columns (first 5 rows)
2. Select rows **50 through 54** using `.iloc`
3. Filter rows where `species == 'versicolor'` and print how many there are
4. Filter rows where `petal length (cm) > 5.0` **AND** `species == 'virginica'`
5. Add a new column `"petal_area"` = `petal length (cm)` × `petal width (cm)` and print the first 5 rows
6. Sort the DataFrame by `petal_area` in **descending** order and print the top 5 rows

> 💡 **Hint:** `df[(df['col1'] > val) & (df['col2'] == 'label')]` — always wrap each condition in `()`.  
> 💡 **Hint:** `df.sort_values('petal_area', ascending=False).head(5)`


In [18]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target_names[iris.target]

# YOUR CODE HERE
# 1. Select sepal length and petal length columns (head 5)

print("Step 1: Sepal length and Petal length (head 5)")
print(iris_df[['sepal length (cm)', 'petal length (cm)']].head())
print()

# 2. Rows 50 through 54 using iloc

print("Step 2: Rows 50 through 54")
print(iris_df.iloc[50:55])
print()

# 3. Filter versicolor species, print count

versicolor_df = iris_df[iris_df['species'] == 'versicolor']
print("Step 3: Number of versicolor rows =", len(versicolor_df))
print()

# 4. Filter: petal length > 5.0 AND species == 'virginica'

virginica_filtered = iris_df[(iris_df['petal length (cm)'] > 5.0) & 
                             (iris_df['species'] == 'virginica')]
print("Step 4: Virginica with petal length > 5.0")
print(virginica_filtered)
print()

# 5. Add petal_area column, print head

iris_df['petal_area'] = iris_df['petal length (cm)'] * iris_df['petal width (cm)']
print("Step 5: First 5 rows with petal_area")
print(iris_df.head())
print()

# 6. Sort by petal_area descending, top 5

top_petal_area = iris_df.sort_values('petal_area', ascending=False).head(5)
print("Step 6: Top 5 rows by petal_area")
print(top_petal_area)

Step 1: Sepal length and Petal length (head 5)
   sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4

Step 2: Rows 50 through 54
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

       species  
50  versicolor  
51  versicolor  
52  versicolor  
53  versicolor  
54  versicolor  

Step 3: Number of versicolor rows = 50

Step 4: Virginica with petal length > 5.0
     sepal length (

## 📝 Task 18 — Capstone: Combined Data Structures Challenge

### Background
Real data science tasks require combining **all** the data structures you have learned. This final task tests your ability to choose the right structure for each job.

### 🎯 Your Task
You are given student records as a **list of dictionaries**:

```python
students = [
    {"name": "Alice",   "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",     "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",   "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",   "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",     "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",   "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",   "scores": [75, 80, 78], "city": "Lahore"},
]
```

Complete each of the following:

1. **Average score:** Add a key `"average"` to each student dict containing the average of their `scores` (round to 2 decimal places). Print all names and averages.

2. **Grade assignment:** Using a dictionary comprehension, create a dict `{name: grade}` where grade is:
   - `"A"` if average ≥ 85
   - `"B"` if average ≥ 70
   - `"C"` if average ≥ 55
   - `"F"` otherwise

3. **Top students:** Use a list comprehension to create a list of **names** of students with average ≥ 80.

4. **Unique cities:** Use a **set** to find all unique cities, then print them.

5. **NumPy statistics:** Convert all scores into a **2D NumPy array** (shape `7×3`). Compute and print:
   - Overall mean, min, max
   - Mean score per student (axis=1)
   - Mean score per test/column (axis=0)

6. **Pandas summary:** Create a **DataFrame** with columns `Name`, `Average`, `Grade`, `City`. Print it, then print the **average score per city** using `.groupby()`.

> 💡 **Hints:**
> - `sum(scores) / len(scores)` or `np.mean(scores)` for averages
> - `np.array([s["scores"] for s in students])` to build the 2D array
> - For the DataFrame, build a list of dicts or use parallel lists


In [19]:
import numpy as np
import pandas as pd

students = [
    {"name": "Alice",  "scores": [85, 90, 78], "city": "Lahore"},
    {"name": "Bob",    "scores": [60, 55, 70], "city": "Karachi"},
    {"name": "Carol",  "scores": [92, 88, 95], "city": "Islamabad"},
    {"name": "David",  "scores": [70, 65, 80], "city": "Lahore"},
    {"name": "Eve",    "scores": [50, 45, 55], "city": "Karachi"},
    {"name": "Frank",  "scores": [88, 92, 84], "city": "Islamabad"},
    {"name": "Grace",  "scores": [75, 80, 78], "city": "Lahore"},
]

# YOUR CODE HERE — Step 1: Add "average" key to each student dict

for s in students:
    s['average'] = round(np.mean(s['scores']), 2)

print("Step 1: Names and Averages")
for s in students:
    print(f"{s['name']}: {s['average']}")
print()

# YOUR CODE HERE — Step 2: Dict comprehension {name: grade}

grades = {s['name']: ('A' if s['average'] >= 85 else
                       'B' if s['average'] >= 70 else
                       'C' if s['average'] >= 55 else 'F')
          for s in students}

print("Step 2: Grades")
print(grades)
print()

# YOUR CODE HERE — Step 3: List of names with average >= 80

top_students = [s['name'] for s in students if s['average'] >= 80]
print("Step 3: Top students (average >= 80)")
print(top_students)
print()

# YOUR CODE HERE — Step 4: Set of unique cities

unique_cities = set(s['city'] for s in students)
print("Step 4: Unique cities")
print(unique_cities)
print()

# YOUR CODE HERE — Step 5: NumPy 2D array and statistics

scores_array = np.array([s['scores'] for s in students])  # shape 7x3
print("Step 5: NumPy statistics")
print("Overall mean:", scores_array.mean())
print("Overall min:", scores_array.min())
print("Overall max:", scores_array.max())
print("Mean score per student (axis=1):", scores_array.mean(axis=1))
print("Mean score per test/column (axis=0):", scores_array.mean(axis=0))
print()

# YOUR CODE HERE — Step 6: Pandas DataFrame and groupby city

df = pd.DataFrame({
    'Name': [s['name'] for s in students],
    'Average': [s['average'] for s in students],
    'Grade': [grades[s['name']] for s in students],
    'City': [s['city'] for s in students]
})

print("Step 6: DataFrame")
print(df)
print()

print("Average score per city:")
print(df.groupby('City')['Average'].mean())

Step 1: Names and Averages
Alice: 84.33
Bob: 61.67
Carol: 91.67
David: 71.67
Eve: 50.0
Frank: 88.0
Grace: 77.67

Step 2: Grades
{'Alice': 'B', 'Bob': 'C', 'Carol': 'A', 'David': 'B', 'Eve': 'F', 'Frank': 'A', 'Grace': 'B'}

Step 3: Top students (average >= 80)
['Alice', 'Carol', 'Frank']

Step 4: Unique cities
{'Islamabad', 'Lahore', 'Karachi'}

Step 5: NumPy statistics
Overall mean: 75.0
Overall min: 45
Overall max: 95
Mean score per student (axis=1): [84.33333333 61.66666667 91.66666667 71.66666667 50.         88.
 77.66666667]
Mean score per test/column (axis=0): [74.28571429 73.57142857 77.14285714]

Step 6: DataFrame
    Name  Average Grade       City
0  Alice    84.33     B     Lahore
1    Bob    61.67     C    Karachi
2  Carol    91.67     A  Islamabad
3  David    71.67     B     Lahore
4    Eve    50.00     F    Karachi
5  Frank    88.00     A  Islamabad
6  Grace    77.67     B     Lahore

Average score per city:
City
Islamabad    89.835
Karachi      55.835
Lahore       77.890


---
## 🤔 Reflection Questions

Answer the following as comments in the cell below:

1. What is the key difference between a **list** and a **tuple**? When would you prefer a tuple?
2. What is the key difference between a **list** and a **set**? Give one real-world use case for each.
3. Why can't a **list** be used as a dictionary key, but a **tuple** can?
4. In Task 15, what is the advantage of NumPy **vectorisation** over using a Python `for` loop?
5. In Task 17, why do we use `&` instead of `and` when filtering a Pandas DataFrame?
6. Looking at the Capstone (Task 18), which data structure did you find most useful? Why?


In [20]:
# Q1: Key difference between a list and a tuple
# A list is mutable (can be changed: add/remove elements), while a tuple is immutable 
# (cannot be changed after creation). Tuples are preferred when you want to store fixed 
# data that should not be modified, e.g., coordinates (x, y) or keys in a dictionary.

# Q2: Key difference between a list and a set
# A list is ordered and can have duplicate elements, while a set is unordered and only 
# stores unique elements. Real-world use case:
# - List: storing students in a class in order of registration.
# - Set: storing unique cities visited by students to avoid duplicates.

# Q3: Why a list can't be used as a dictionary key, but a tuple can
# Dictionary keys must be hashable and immutable. Lists are mutable and unhashable, so 
# they cannot be keys.Tuples are immutable and hashable, so they can safely be used as 
# dictionary keys.

# Q4: Advantage of NumPy vectorisation over Python for loop
# Vectorisation performs operations on entire arrays at once, which is faster and more 
# memory-efficient than looping through elements in Python.

# Q5: Why we use '&' instead of 'and' in Pandas filtering
# '&' performs element-wise logical AND on Series or DataFrame columns.
# 'and' cannot be used on Pandas Series because it only works with single boolean values, 
# not arrays of booleans.

# Q6: Most useful data structure in Task 18
# The dictionary was most useful for storing student records because it allowed easy 
# access to each student's name, scores, and city. Combining dicts with NumPy and Pandas 
# made calculations, aggregations, and tabular analysis straightforward and efficient.